apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: foo
        ports:
        - containerPort: 8080
          name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: bar
        ports:
        - containerPort: 8080
          name: app
---
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  ports:
  - port: 80
    name: foo
    targetPort: app
  selector:
    app: foo
---
apiVersion: v1
kind: Service
metadata:
  name: bar
spec:
  ports:
  - port: 80
    targetPort: app
    name: bar
  selector:
    app: bar
