from golang:1.15 as builder

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test -v ./...
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./...

FROM scratch
WORKDIR /app
COPY --from=builder /app/app /app
CMD ["/app/app", "-l", "foo"]
